### ISSUE TITLE
Acceso al sistema

### ISSUE THREAD

**Issue by acuellargit** [inteli-code/ERPTAPIA#25]
En el acceso actualmente el sistema tiene por default accesar por medio del puerto 3306 se debe de cambiar al puerto 3307.

**Comment by INTELI-RANGEL** [comment]
El valor del puerto se graba en el registro del sistema cada vez que se entra al sistema, si se cambia una vez este valor cuando vuelva a entrar al sistema pondrá por dafault el valor que se cambió

**Comment by acuellargit** [comment]
negativo el sistema erp inteligent NO LO HACE ASI.  CHECALO POR FAVOR
